### ISSUE TITLE
Getting Error "Your chart rendered a <clipPath /> node which isn't supported by <ReactPDFChart /> yet"

### ISSUE THREAD

**Issue by eugeneZolotarenko** [EvHaus/react-pdf-charts#11]
First of all, thank you for your work. This library has the potential to solve my current problem.

I'm trying to render your example in the <ReactPDFChart /> component but I'm getting the "Your chart rendered a <clipPath /> node which isn't supported by <ReactPDFChart /> yet" error. 

I have the last version of recharts and react-pdf. What could be a problem? How can we solve it?

**Comment by EvHaus** [comment]
Hmm, how are you running the examples?

**Comment by eugeneZolotarenko** [comment]
I basically copied your example and try to load it inside the <Page /> component of the @react-pdf/renderer library.
I have React application based on create-react-app with React 18.2

I'm also getting this JSX error.
![Screenshot 2023-06-29 at 10 11 21](https://github.com/EvHaus/react-pdf-charts/assets/45913460/2f80eec7-5d36-4d22-86a4-e8e8d703b511)

**Comment by EvHaus** [comment]
The original version only supported server-side rendering. I just published v0.0.4 with support for client-side rendering too. Can you please try it?

Here's how it should work: https://stackblitz.com/edit/react-starter-typescript-wt7dfb?file=index.tsx
