### ISSUE TITLE
LinearGradient not working for fill of custom dot for <Line />

### ISSUE THREAD

**Issue by PieterT2000** [EvHaus/react-pdf-charts#523]
### Describe the bug

`fill` attribute values that link to a linearGradient definition won't work correctly. Instead of the gradient, a transparent fill is shown. For context, this happened when I tried to apply a gradient background (fill) to a custom dot shape in the Recharts LineChart component. 

### Reproduction

[StackBlitz minimal reproduction](https://stackblitz.com/edit/vitejs-vite-wjcpetuo?file=src%2Fcomponents%2FReactPdfWrappedChart.tsx)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/EvHaus/react-pdf-charts/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that you're confident that this is a legitimate bug. To ask a question open a [GitHub Discussion](https://github.com/EvHaus/react-pdf-charts/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by EvHaus** [comment]
Looks like this is a bug with `react-pdf` itself. I've logged the ticket:

- diegomura/react-pdf#3003

**Comment by PieterT2000** [comment]
Thanks, @EvHaus! The gradient is still missing in the PDF, even when all stop opacities are set to 1.

**Comment by EvHaus** [comment]
Looks like that another bug with `react-pdf`. :( I've logged a new ticket:

- diegomura/react-pdf#3004

I think I might be able to work around this one by merging any `<defs>` I find into a single one. I'll give that a try when I have a chance and ship a new version if that works.

**Comment by PieterT2000** [comment]
Thanks for the tip, @EvHaus; I've added a fix. Let me know your thoughts when you get time.
